// ════════════════════════════════════════════════════════════════════════
// crm-invoice-pdf.ts
//
// Generates a client-ready PDF for a CRM invoice. Uses pdf-lib (same
// engine as src/lib/audit-trail-pdf.ts) so it runs on Vercel's node
// runtime without Chromium. Layout:
//
//   ┌────────────────────────────────────────────────────────┐
//   │  [logo]                         INVOICE                │
//   │  Firm name                      MP-2026-0042           │
//   │  Firm address                   Issue: 15 Apr 2026     │
//   │  Firm VAT · matricule           Due:   15 May 2026     │
//   ├────────────────────────────────────────────────────────┤
//   │  Bill to                                               │
//   │  Client name                                           │
//   │  Client address                                        │
//   │  Matter: MP-2026-0001 · Fund formation advice          │
//   ├────────────────────────────────────────────────────────┤
//   │  # │ Description              │ Qty │ Rate │  Amount  │
//   ├────┼──────────────────────────┼─────┼──────┼──────────┤
//   │  1 │ …                        │  … │  …  │       … │
//   ├────┴──────────────────────────┴─────┴──────┴──────────┤
//   │                          Subtotal (excl. VAT)  €X,XXX │
//   │                          VAT (17%)              €  XX │
//   │                          ─────────────────────────────│
//   │                          TOTAL                 €X,XXX │
//   ├────────────────────────────────────────────────────────┤
//   │  Payment instructions                                  │
//   │  Bank · IBAN · BIC · Reference: MP-2026-0042           │
//   │                                                        │
//   │  Footer text (firm terms / boilerplate)                │
//   └────────────────────────────────────────────────────────┘
//
// The PDF intentionally has NO "generated by cifra" branding — it's
// the firm's commercial document, not ours.
// ════════════════════════════════════════════════════════════════════════

import { PDFDocument, StandardFonts, rgb, type PDFFont, type PDFPage } from 'pdf-lib';
import { queryOne } from '@/lib/db';
import { getFirmSettings, type FirmSettings } from '@/lib/crm-firm-settings';

const NAVY   = rgb(0x1a / 255, 0x1a / 255, 0x2e / 255);
const GREY   = rgb(0x6b / 255, 0x72 / 255, 0x80 / 255);
const DARK   = rgb(0x11 / 255, 0x18 / 255, 0x27 / 255);
const BORDER = rgb(0xe5 / 255, 0xe7 / 255, 0xeb / 255);
const STRIPE = rgb(0xfa / 255, 0xfa / 255, 0xfb / 255);
const BRAND  = rgb(0x0f / 255, 0x3d / 255, 0x56 / 255);   // navy/teal — firm-neutral

const PAGE_W = 595.28;   // A4
const PAGE_H = 841.89;
const MARGIN = 50;

type FontSet = { regular: PDFFont; bold: PDFFont; oblique: PDFFont };

interface LineItem {
  description?: string;
  quantity?: number | string;
  rate?: number | string;
  amount?: number | string;
  // Some imports store 'hours' + 'rate_eur' — we tolerate both shapes.
  hours?: number | string;
  rate_eur?: number | string;
}

interface InvoiceRow {
  id: string;
  invoice_number: string;
  issue_date: string | null;
  due_date: string | null;
  currency: string | null;
  amount_excl_vat: number | string | null;
  vat_rate: number | string | null;
  vat_amount: number | string | null;
  amount_incl_vat: number | string | null;
  amount_paid: number | string | null;
  status: string;
  payment_method: string | null;
  payment_reference: string | null;
  line_items: unknown;
  notes: string | null;
  client_name: string | null;
  client_address_billing: string | null;
  client_vat: string | null;
  matter_reference: string | null;
  matter_title: string | null;
}

export interface InvoicePDFResult {
  buffer: Buffer;
  filename: string;
}

/**
 * Build a PDF for a single CRM invoice. Queries the invoice + its
 * client + its matter in one round-trip so the PDF is consistent with
 * what the user saw when they clicked "Download".
 */
export async function buildInvoicePDF(invoiceId: string): Promise<InvoicePDFResult> {
  const [inv, firm] = await Promise.all([
    queryOne<InvoiceRow>(
      `SELECT b.id, b.invoice_number, b.issue_date::text AS issue_date,
              b.due_date::text AS due_date, b.currency,
              b.amount_excl_vat, b.vat_rate, b.vat_amount, b.amount_incl_vat,
              b.amount_paid, b.status, b.payment_method, b.payment_reference,
              b.line_items, b.notes,
              c.company_name AS client_name,
              c.billing_address AS client_address_billing,
              c.vat_number AS client_vat,
              m.matter_reference, m.title AS matter_title
         FROM crm_billing_invoices b
         LEFT JOIN crm_companies c ON c.id = b.company_id
         LEFT JOIN crm_matters   m ON m.id = b.matter_id
        WHERE b.id = $1`,
      [invoiceId],
    ),
    getFirmSettings(),
  ]);
  if (!inv) throw new Error('Invoice not found');

  const lineItems = normaliseLineItems(inv.line_items);
  const ccy = inv.currency ?? 'EUR';

  const pdf = await PDFDocument.create();
  pdf.setTitle(`Invoice ${inv.invoice_number}`);
  pdf.setAuthor(firm.firm_name);
  pdf.setSubject(`Invoice ${inv.invoice_number} · ${firm.firm_name}`);
  pdf.setCreator(firm.firm_name);

  const fonts: FontSet = {
    regular: await pdf.embedFont(StandardFonts.Helvetica),
    bold:    await pdf.embedFont(StandardFonts.HelveticaBold),
    oblique: await pdf.embedFont(StandardFonts.HelveticaOblique),
  };

  let page = pdf.addPage([PAGE_W, PAGE_H]);

  // ─── Header ─────────────────────────────────────────────
  let y = drawHeader(page, fonts, firm, inv);

  // ─── Bill-to block ──────────────────────────────────────
  y = drawBillTo(page, fonts, inv, y);

  // ─── Line items table ───────────────────────────────────
  const tableResult = drawLineItemsTable(pdf, page, fonts, lineItems, ccy, y);
  page = tableResult.page;
  y = tableResult.y;

  // ─── Totals ─────────────────────────────────────────────
  y = drawTotals(page, fonts, inv, ccy, y);

  // ─── Payment instructions ───────────────────────────────
  y = drawPaymentInstructions(page, fonts, firm, inv, y);

  // ─── Notes (if any) ─────────────────────────────────────
  if (inv.notes && inv.notes.trim()) {
    y = drawNotes(page, fonts, inv.notes, y);
  }

  // ─── Footer ─────────────────────────────────────────────
  drawFooter(page, fonts, firm);

  const bytes = await pdf.save();
  return {
    buffer: Buffer.from(bytes),
    filename: `${sanitiseFilename(inv.invoice_number)}.pdf`,
  };
}

// ═══════════════════════════════════════════════════════════════════
// Helpers
// ═══════════════════════════════════════════════════════════════════

function drawHeader(page: PDFPage, fonts: FontSet, firm: FirmSettings, inv: InvoiceRow): number {
  // Left: firm identity.
  let ly = PAGE_H - MARGIN;
  page.drawText(firm.firm_name, { x: MARGIN, y: ly, size: 16, font: fonts.bold, color: BRAND });
  ly -= 20;

  for (const line of firm.firm_address_lines) {
    page.drawText(line, { x: MARGIN, y: ly, size: 9, font: fonts.regular, color: DARK });
    ly -= 11;
  }
  const metaBits: string[] = [];
  if (firm.firm_vat_number) metaBits.push(`VAT ${firm.firm_vat_number}`);
  if (firm.firm_matricule)  metaBits.push(`Matricule ${firm.firm_matricule}`);
  if (firm.firm_rcs_number) metaBits.push(`RCS ${firm.firm_rcs_number}`);
  if (metaBits.length > 0) {
    page.drawText(metaBits.join('  ·  '), { x: MARGIN, y: ly, size: 8, font: fonts.regular, color: GREY });
    ly -= 11;
  }
  const contactBits: string[] = [];
  if (firm.firm_email)   contactBits.push(firm.firm_email);
  if (firm.firm_phone)   contactBits.push(firm.firm_phone);
  if (firm.firm_website) contactBits.push(firm.firm_website);
  if (contactBits.length > 0) {
    page.drawText(contactBits.join('  ·  '), { x: MARGIN, y: ly, size: 8, font: fonts.regular, color: GREY });
    ly -= 11;
  }

  // Right: INVOICE block.
  const rightX = PAGE_W - MARGIN;
  let ry = PAGE_H - MARGIN;
  const titleW = fonts.bold.widthOfTextAtSize('INVOICE', 20);
  page.drawText('INVOICE', { x: rightX - titleW, y: ry, size: 20, font: fonts.bold, color: DARK });
  ry -= 24;

  const numLabel = 'No.';
  const num = inv.invoice_number;
  const numW = fonts.bold.widthOfTextAtSize(num, 12);
  page.drawText(numLabel, { x: rightX - numW - 30, y: ry, size: 9, font: fonts.regular, color: GREY });
  page.drawText(num, { x: rightX - numW, y: ry, size: 12, font: fonts.bold, color: DARK });
  ry -= 16;

  if (inv.issue_date) {
    ry = drawLabelValueRight(page, fonts, 'Issue date', formatDate(inv.issue_date), rightX, ry);
  }
  if (inv.due_date) {
    ry = drawLabelValueRight(page, fonts, 'Due date', formatDate(inv.due_date), rightX, ry);
  }
  if (inv.status && inv.status !== 'draft') {
    const statusLabel = inv.status.toUpperCase().replace(/_/g, ' ');
    ry = drawLabelValueRight(page, fonts, 'Status', statusLabel, rightX, ry);
  }

  return Math.min(ly, ry) - 14;
}

function drawLabelValueRight(
  page: PDFPage, fonts: FontSet, label: string, value: string, rightX: number, y: number,
): number {
  const valW = fonts.regular.widthOfTextAtSize(value, 9);
  page.drawText(label, { x: rightX - valW - fonts.regular.widthOfTextAtSize(label, 8) - 8, y, size: 8, font: fonts.regular, color: GREY });
  page.drawText(value, { x: rightX - valW, y, size: 9, font: fonts.regular, color: DARK });
  return y - 12;
}

function drawBillTo(page: PDFPage, fonts: FontSet, inv: InvoiceRow, startY: number): number {
  let y = startY;
  // Divider
  page.drawLine({ start: { x: MARGIN, y }, end: { x: PAGE_W - MARGIN, y }, thickness: 0.5, color: BORDER });
  y -= 16;

  page.drawText('BILL TO', { x: MARGIN, y, size: 8, font: fonts.bold, color: GREY });
  y -= 14;

  if (inv.client_name) {
    page.drawText(inv.client_name, { x: MARGIN, y, size: 11, font: fonts.bold, color: DARK });
    y -= 14;
  }
  if (inv.client_address_billing) {
    for (const line of String(inv.client_address_billing).split(/\r?\n/).filter(Boolean)) {
      page.drawText(line, { x: MARGIN, y, size: 9, font: fonts.regular, color: DARK });
      y -= 11;
    }
  }
  if (inv.client_vat) {
    page.drawText(`VAT ${inv.client_vat}`, { x: MARGIN, y, size: 8, font: fonts.regular, color: GREY });
    y -= 11;
  }

  // Matter reference on the right column
  if (inv.matter_reference) {
    const mRef = inv.matter_reference;
    const mTitle = inv.matter_title ?? '';
    const col2X = PAGE_W / 2 + 20;
    let my = startY - 16 - 14;
    page.drawText('MATTER', { x: col2X, y: my + 14, size: 8, font: fonts.bold, color: GREY });
    page.drawText(mRef, { x: col2X, y: my, size: 11, font: fonts.bold, color: DARK });
    my -= 14;
    if (mTitle) {
      const wrapped = wrapText(fonts.regular, 9, mTitle, PAGE_W - MARGIN - col2X);
      for (const line of wrapped) {
        page.drawText(line, { x: col2X, y: my, size: 9, font: fonts.regular, color: DARK });
        my -= 11;
      }
    }
  }

  return y - 10;
}

interface TableResult { page: PDFPage; y: number; }

function drawLineItemsTable(
  pdf: PDFDocument, pageIn: PDFPage, fonts: FontSet, items: LineItem[], ccy: string, startY: number,
): TableResult {
  let page = pageIn;
  let y = startY;

  const cols = [
    { key: '#',        w: 25,  align: 'left'  as const },
    { key: 'Description', w: 285, align: 'left'  as const },
    { key: 'Qty',      w: 50,  align: 'right' as const },
    { key: 'Rate',     w: 65,  align: 'right' as const },
    { key: 'Amount',   w: 70,  align: 'right' as const },
  ];
  const tableX = MARGIN;
  const tableW = cols.reduce((s, c) => s + c.w, 0);
  const rowH = 20;
  const headerH = 22;

  // Header row
  page.drawRectangle({ x: tableX, y: y - headerH, width: tableW, height: headerH, color: rgb(0.95, 0.96, 0.98) });
  let cx = tableX + 8;
  for (const c of cols) {
    const text = c.key.toUpperCase();
    const textW = fonts.bold.widthOfTextAtSize(text, 8);
    const tx = c.align === 'right' ? cx + c.w - textW - 16 : cx;
    page.drawText(text, { x: tx, y: y - 14, size: 8, font: fonts.bold, color: GREY });
    cx += c.w;
  }
  y -= headerH;

  // Rows
  items.forEach((it, i) => {
    if (y - rowH < MARGIN + 180) {
      // Not enough room for row + totals block — new page
      page = pdf.addPage([PAGE_W, PAGE_H]);
      y = PAGE_H - MARGIN - 20;
    }
    if (i % 2 === 1) {
      page.drawRectangle({ x: tableX, y: y - rowH, width: tableW, height: rowH, color: STRIPE });
    }

    const qty = numOrNull(it.quantity ?? it.hours);
    const rate = numOrNull(it.rate ?? it.rate_eur);
    const amount = numOrNull(it.amount) ?? (qty !== null && rate !== null ? qty * rate : null);

    const values = [
      String(i + 1),
      truncate(String(it.description ?? '—'), 60),
      qty !== null ? formatQty(qty) : '',
      rate !== null ? formatMoney(rate, ccy) : '',
      amount !== null ? formatMoney(amount, ccy) : '',
    ];

    let cx2 = tableX + 8;
    cols.forEach((c, ci) => {
      const text = values[ci];
      const textW = fonts.regular.widthOfTextAtSize(text, 9);
      const tx = c.align === 'right' ? cx2 + c.w - textW - 16 : cx2;
      page.drawText(text, { x: tx, y: y - 13, size: 9, font: fonts.regular, color: DARK });
      cx2 += c.w;
    });
    y -= rowH;
  });

  if (items.length === 0) {
    page.drawText('(No line items)', { x: tableX + 8, y: y - 13, size: 9, font: fonts.oblique, color: GREY });
    y -= rowH;
  }

  // Bottom border
  page.drawLine({ start: { x: tableX, y }, end: { x: tableX + tableW, y }, thickness: 0.5, color: BORDER });

  return { page, y: y - 14 };
}

function drawTotals(page: PDFPage, fonts: FontSet, inv: InvoiceRow, ccy: string, startY: number): number {
  const rightX = PAGE_W - MARGIN;
  let y = startY;

  const excl = numOrNull(inv.amount_excl_vat) ?? 0;
  const vatRate = numOrNull(inv.vat_rate);
  const vatAmt = numOrNull(inv.vat_amount) ?? 0;
  const incl = numOrNull(inv.amount_incl_vat) ?? (excl + vatAmt);
  const paid = numOrNull(inv.amount_paid) ?? 0;
  const outstanding = incl - paid;

  y = drawTotalLine(page, fonts, 'Subtotal (excl. VAT)', formatMoney(excl, ccy), rightX, y, false);
  const vatLabel = vatRate !== null ? `VAT (${(vatRate * 100).toFixed(0)}%)` : 'VAT';
  y = drawTotalLine(page, fonts, vatLabel, formatMoney(vatAmt, ccy), rightX, y, false);

  // Divider above the grand total
  page.drawLine({ start: { x: PAGE_W / 2, y: y + 4 }, end: { x: rightX, y: y + 4 }, thickness: 0.5, color: BORDER });

  y = drawTotalLine(page, fonts, 'TOTAL', formatMoney(incl, ccy), rightX, y, true);

  if (paid > 0) {
    y = drawTotalLine(page, fonts, 'Paid to date', `−${formatMoney(paid, ccy)}`, rightX, y, false);
    page.drawLine({ start: { x: PAGE_W / 2, y: y + 4 }, end: { x: rightX, y: y + 4 }, thickness: 0.5, color: BORDER });
    y = drawTotalLine(page, fonts, 'OUTSTANDING', formatMoney(outstanding, ccy), rightX, y, true);
  }

  return y - 10;
}

function drawTotalLine(
  page: PDFPage, fonts: FontSet, label: string, value: string, rightX: number, y: number, bold: boolean,
): number {
  const size = bold ? 11 : 9;
  const font = bold ? fonts.bold : fonts.regular;
  const color = bold ? DARK : DARK;
  const valW = font.widthOfTextAtSize(value, size);
  const labelW = font.widthOfTextAtSize(label, size);
  page.drawText(label, { x: rightX - valW - labelW - 20, y, size, font, color: bold ? DARK : GREY });
  page.drawText(value, { x: rightX - valW, y, size, font, color });
  return y - (bold ? 16 : 13);
}

function drawPaymentInstructions(
  page: PDFPage, fonts: FontSet, firm: FirmSettings, inv: InvoiceRow, startY: number,
): number {
  let y = startY;
  page.drawLine({ start: { x: MARGIN, y }, end: { x: PAGE_W - MARGIN, y }, thickness: 0.5, color: BORDER });
  y -= 14;

  page.drawText('PAYMENT INSTRUCTIONS', { x: MARGIN, y, size: 8, font: fonts.bold, color: GREY });
  y -= 14;

  const lines: string[] = [];
  if (firm.bank_name) lines.push(`Bank: ${firm.bank_name}`);
  if (firm.bank_iban) lines.push(`IBAN: ${firm.bank_iban}`);
  if (firm.bank_bic)  lines.push(`BIC:  ${firm.bank_bic}`);
  const ref = inv.payment_reference ?? inv.invoice_number;
  lines.push(`Reference: ${ref}`);
  if (firm.payment_terms_days) {
    lines.push(`Payment terms: ${firm.payment_terms_days} days from issue date.`);
  }

  for (const line of lines) {
    page.drawText(line, { x: MARGIN, y, size: 9, font: fonts.regular, color: DARK });
    y -= 12;
  }
  return y - 4;
}

function drawNotes(page: PDFPage, fonts: FontSet, notes: string, startY: number): number {
  let y = startY - 6;
  page.drawText('NOTES', { x: MARGIN, y, size: 8, font: fonts.bold, color: GREY });
  y -= 13;
  const wrapped = wrapText(fonts.regular, 9, notes, PAGE_W - MARGIN * 2);
  for (const line of wrapped) {
    if (y < MARGIN + 30) break;    // avoid smashing into footer
    page.drawText(line, { x: MARGIN, y, size: 9, font: fonts.regular, color: DARK });
    y -= 11;
  }
  return y - 6;
}

function drawFooter(page: PDFPage, fonts: FontSet, firm: FirmSettings): void {
  // Footer text from settings (firm's legal boilerplate)
  if (firm.footer_text) {
    const wrapped = wrapText(fonts.oblique, 7, firm.footer_text, PAGE_W - MARGIN * 2);
    let y = 40;
    for (const line of wrapped.slice(0, 3)) {
      const tw = fonts.oblique.widthOfTextAtSize(line, 7);
      page.drawText(line, { x: (PAGE_W - tw) / 2, y, size: 7, font: fonts.oblique, color: GREY });
      y -= 9;
    }
  }
  // Page frame at the very bottom is intentionally omitted — a tidy
  // invoice needs air, not lines.
}

// ─── Utilities ─────────────────────────────────────────────

function normaliseLineItems(raw: unknown): LineItem[] {
  if (!Array.isArray(raw)) return [];
  return raw.filter((x): x is LineItem => x && typeof x === 'object');
}

function numOrNull(v: unknown): number | null {
  if (v === null || v === undefined || v === '') return null;
  const n = Number(v);
  return Number.isFinite(n) ? n : null;
}

function formatMoney(n: number, ccy: string): string {
  const sign = ccy === 'EUR' ? '€' : ccy === 'GBP' ? '£' : ccy === 'USD' ? '$' : '';
  const body = n.toLocaleString('en-GB', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
  return sign ? `${sign}${body}` : `${body} ${ccy}`;
}

function formatQty(n: number): string {
  // Integer if whole, else up to 2 decimals.
  return Number.isInteger(n) ? String(n) : n.toFixed(2);
}

function formatDate(iso: string): string {
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return iso;
  return d.toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' });
}

function wrapText(font: PDFFont, size: number, text: string, maxWidth: number): string[] {
  const out: string[] = [];
  for (const paragraph of text.split(/\r?\n/)) {
    const words = paragraph.split(/\s+/).filter(Boolean);
    let line = '';
    for (const w of words) {
      const candidate = line ? `${line} ${w}` : w;
      if (font.widthOfTextAtSize(candidate, size) <= maxWidth) {
        line = candidate;
      } else {
        if (line) out.push(line);
        line = w;
      }
    }
    if (line) out.push(line);
    if (!words.length) out.push('');
  }
  return out;
}

function truncate(s: string, max: number): string {
  if (s.length <= max) return s;
  return s.slice(0, max - 1) + '…';
}

function sanitiseFilename(s: string): string {
  return s.replace(/[^a-zA-Z0-9._-]+/g, '_');
}

// Silence unused lint for NAVY now that the header palette settled
// without using it (kept in the const table for future logo tinting).
void NAVY;
