'use client';

// ════════════════════════════════════════════════════════════════════════
// EmailDrafterModal — modal dialog that calls the draft-email agent and
// lets the reviewer edit + copy + open-in-mail-client the generated text.
//
// Extracted from page.tsx during the 2026-04-18 refactor. Verbatim move.
// ════════════════════════════════════════════════════════════════════════

import { useEffect, useState } from 'react';
import { IconBtn, Spinner } from './_atoms';

interface ApproverSlim {
  id: string;
  name: string;
  email: string | null;
  role: string | null;
  organization: string | null;
  country: string | null;
  approver_type: 'client' | 'csp' | 'other';
  is_primary: boolean;
}

interface DraftResponse {
  subject: string;
  body: string;
  model: string;
  approvers: ApproverSlim[];
  primary_email: string | null;
  cc_emails: string[];
}

export function EmailDrafterModal({
  declarationId, onClose,
}: { declarationId: string; onClose: () => void }) {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [draft, setDraft] = useState<DraftResponse | null>(null);
  const [subject, setSubject] = useState('');
  const [body, setBody] = useState('');
  const [expertNotes, setExpertNotes] = useState('');
  const [copied, setCopied] = useState(false);

  async function generate() {
    setLoading(true); setError(null);
    try {
      const res = await fetch('/api/agents/draft-email', {
        method: 'POST', headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ declaration_id: declarationId, expert_notes: expertNotes || null }),
      });
      if (!res.ok) throw new Error((await res.json()).error || 'Failed');
      const d = await res.json() as DraftResponse;
      setDraft(d);
      setSubject(d.subject);
      setBody(d.body);
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e));
    } finally {
      setLoading(false);
    }
  }

  function copyAll() {
    const full = `Subject: ${subject}\n\n${body}`;
    navigator.clipboard.writeText(full).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    });
  }

  function openInMail() {
    // Pre-fill To / Cc from the entity's approvers when available.
    const to = draft?.primary_email ? encodeURIComponent(draft.primary_email) : '';
    const cc = draft?.cc_emails && draft.cc_emails.length > 0
      ? `&cc=${encodeURIComponent(draft.cc_emails.join(','))}`
      : '';
    const url = `mailto:${to}?subject=${encodeURIComponent(subject)}${cc}&body=${encodeURIComponent(body)}`;
    window.location.href = url;
  }

  useEffect(() => {
    const onEsc = (e: KeyboardEvent) => { if (e.key === 'Escape') onClose(); };
    window.addEventListener('keydown', onEsc);
    return () => window.removeEventListener('keydown', onEsc);
  }, [onClose]);

  return (
    <div
      className="fixed inset-0 z-50 bg-black/40 flex items-center justify-center p-4 animate-fadeIn"
      role="dialog"
      aria-modal="true"
      aria-labelledby="email-drafter-title"
    >
      <div className="bg-surface rounded-lg w-full max-w-3xl shadow-2xl flex flex-col" style={{ maxHeight: '90vh' }}>
        <div className="px-5 py-3 border-b border-border flex items-center justify-between">
          <div>
            <h3 id="email-drafter-title" className="text-base font-semibold text-ink">Draft client email</h3>
            <div className="text-xs text-ink-muted mt-0.5">Generated by Claude — review carefully before sending.</div>
          </div>
          <IconBtn title="Close (Esc)" onClick={onClose}>
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/></svg>
          </IconBtn>
        </div>

        <div className="flex-1 overflow-y-auto p-5">
          {!draft && !loading && (
            <div>
              <label className="block text-xs uppercase tracking-wide font-semibold text-ink-muted mb-1.5">
                Expert notes (optional)
              </label>
              <textarea
                value={expertNotes}
                onChange={e => setExpertNotes(e.target.value)}
                rows={4}
                placeholder="Specific legal observations, position changes, AED considerations… these will be quoted verbatim in the email."
                className="w-full border border-border-strong rounded px-3 py-2 text-sm"
              />
              <button
                onClick={generate}
                className="mt-3 h-9 px-4 rounded bg-brand-500 text-white text-sm font-semibold hover:bg-brand-600 transition-all duration-150 cursor-pointer"
              >
                Generate draft
              </button>
            </div>
          )}

          {loading && (
            <div className="flex items-center justify-center py-10 text-sm text-ink-muted gap-2">
              <Spinner /> Drafting with Claude (Opus)…
            </div>
          )}

          {error && (
            <div className="text-sm text-red-700 bg-red-50 border border-red-200 rounded px-3 py-2">
              {error}
            </div>
          )}

          {draft && (
            <div className="space-y-3">
              {/* Approvers preview — so the reviewer knows who the mail
                  client will address when they click "Open in mail". */}
              {draft.approvers.length > 0 ? (
                <div>
                  <label className="block text-xs uppercase tracking-wide font-semibold text-ink-muted mb-1.5">
                    Recipients (from entity approvers)
                  </label>
                  <div className="flex flex-wrap gap-1.5">
                    {draft.approvers.map(a => (
                      <span
                        key={a.id}
                        className={[
                          'inline-flex items-center gap-1 px-2 py-0.5 rounded border text-xs',
                          a.is_primary
                            ? 'bg-brand-50 text-brand-700 border-brand-200'
                            : 'bg-surface-alt text-ink-soft border-border',
                        ].join(' ')}
                      >
                        <span className="text-2xs font-bold uppercase">{a.is_primary ? 'To' : 'Cc'}</span>
                        <span className="font-medium">{a.name}</span>
                        {a.email && <span className="text-ink-muted font-mono text-2xs">{a.email}</span>}
                      </span>
                    ))}
                  </div>
                </div>
              ) : (
                <div className="text-xs text-warning-800 bg-warning-50 border border-warning-200 rounded px-3 py-2">
                  No approvers configured for this entity. Add them on the
                  entity page so &ldquo;Open in mail&rdquo; can pre-fill To / Cc.
                </div>
              )}

              <div>
                <label className="block text-xs uppercase tracking-wide font-semibold text-ink-muted mb-1.5">Subject</label>
                <input
                  value={subject}
                  onChange={e => setSubject(e.target.value)}
                  className="w-full border border-border-strong rounded px-3 py-2 text-sm font-medium"
                />
              </div>
              <div>
                <label className="block text-xs uppercase tracking-wide font-semibold text-ink-muted mb-1.5">Body</label>
                <textarea
                  value={body}
                  onChange={e => setBody(e.target.value)}
                  rows={18}
                  className="w-full border border-border-strong rounded px-3 py-2 text-sm font-mono leading-relaxed"
                />
              </div>
              <div className="text-2xs text-ink-faint">Generated by {draft.model}</div>
            </div>
          )}
        </div>

        {draft && (
          <div className="px-5 py-3 border-t border-border bg-surface-alt flex items-center justify-end gap-2">
            <button
              onClick={generate}
              className="h-8 px-3 rounded border border-border-strong text-xs font-medium text-ink-soft hover:bg-surface hover:border-gray-400 transition-all duration-150 cursor-pointer"
            >
              Re-generate
            </button>
            <button
              onClick={copyAll}
              className="h-8 px-3 rounded border border-border-strong text-xs font-medium text-ink-soft hover:bg-surface hover:border-gray-400 transition-all duration-150 cursor-pointer"
            >
              {copied ? '✓ Copied' : 'Copy'}
            </button>
            <button
              onClick={openInMail}
              className="h-8 px-3 rounded bg-brand-500 text-white text-xs font-semibold hover:bg-brand-600 transition-all duration-150 cursor-pointer"
            >
              Open in mail client
            </button>
          </div>
        )}
      </div>
    </div>
  );
}
